### ISSUE TITLE
AMD support broken

### ISSUE THREAD

**Issue by thijstriemstra** [theonion/videojs-persistvolume#11]
Video.js [exports itself as a named AMD module](https://github.com/videojs/video.js/commit/42fbd4c7994679ba2b44ff73ed450d5c2c6c4836) called `videojs`. Your script refers to `video.js` and its throwing a 404 for `video.js` while my other `videojs` requires work fine.

**Comment by thijstriemstra** [comment]
I'm not sure what causes the issue but I'll revert to the previous version for now.

**Comment by ngocketit** [comment]
This repos hasn't been left behind with the latest development of videos. As you pointed out, `define(['./video'],...)` is wrong but `define(['videos'],...)` no longer works with videojs version 5. So, use this instead: `define(['video.js'],...)`.

**Comment by thijstriemstra** [comment]
> This repos hasn't been left behind 

I think it has: it's not maintained any longer.
